name: usrun
description: HCMUS Run

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  android_intent: ^0.3.7+2
  crypto: ^2.1.3
  flutter_map: ^0.8.2
  latlong: ^0.6.1
  geolocator: ^5.0.0
  path: 1.7.0
  location:
    path: ./myLibs/location_plugin
  sensors: ^0.4.1+8

  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.16.1

  google_maps_flutter: ^0.5.25+1
  pedometer: ^1.2.0
  reflectable: any
  
  image_picker: ^0.6.1+8
  image_cropper: ^1.2.2
  shared_preferences: ^0.5.0
  sprintf: ^4.0.2
  gradient_app_bar: ^0.1.3
  flutter_launcher_icons: ^0.7.4
  date_format: ^1.0.8
  lite_rolling_switch: ^0.1.1
  photo_view: ^0.9.2
  nuts_activity_indicator: ^0.1.1
  intl: ^0.16.1
  flutter_widgets: ^0.1.11
  carousel_pro: ^1.0.0
  flutter_staggered_animations: ^0.1.2
  
  path_provider: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  http: ^0.12.0+4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/usrunlogo/app-icon.png" 
  adaptive_icon_background: "assets/usrunlogo/background.png"
  adaptive_icon_foreground: "assets/usrunlogo/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/localization/en.json
    - assets/localization/vi.json

    - assets/images/welcome.png
    - assets/images/login_fb_en.png
    - assets/images/login_fb_vi.png
    - assets/images/login_email_en.png
    - assets/images/login_email_vi.png
    - assets/images/login_gg_en.png
    - assets/images/login_gg_vi.png
    - assets/images/or_line.png

    - assets/images/drawer_background.png
    - assets/images/drawer_background_darker.png
    - assets/images/avatar.png
    - assets/images/small_default_image.png
    - assets/images/static_stats_chart_01.png
    - assets/images/static_stats_chart_02.png
    - assets/images/static_stats_chart_03.png

    - assets/images/avatar_huyta.png
    - assets/images/avatar_quoctk.png
    - assets/images/avatar_ngocvtt.png
    - assets/images/avatar_phuctt.png
    - assets/images/avatar_khatm.png

    - assets/myicons/icon-white-back.png
    - assets/myicons/icon-orange-close.png
    - assets/myicons/icon-orange-search.png
    - assets/myicons/icon-white-search.png
    - assets/myicons/icon-big-white-check.png
    - assets/myicons/icon-white-image-default.png
    - assets/myicons/icon-black-image-default.png
    - assets/myicons/icon-color-stars.png
    - assets/myicons/icon-color-letter.png
    - assets/myicons/icon-color-developers.png
    - assets/myicons/icon-color-update-version.png
    - assets/myicons/icon-black-next.png
    - assets/myicons/icon-white-next.png
    - assets/myicons/icon-white-edit.png
    - assets/myicons/icon-black-edit.png
    - assets/myicons/icon-color-finish.png
    - assets/myicons/icon-black-people.png
    - assets/myicons/icon-white-people.png
    - assets/myicons/icon-black-heart-beat.png
    - assets/myicons/icon-black-footstep.png
    - assets/myicons/icon-black-elevation.png
    - assets/myicons/icon-black-calories.png
    - assets/myicons/icon-black-time.png
    - assets/myicons/icon-black-speed-ometer.png
    - assets/myicons/icon-black-road.png
    - assets/myicons/icon-black-runner-02.png
    - assets/myicons/icon-white-heart-beat.png
    - assets/myicons/icon-white-footstep.png
    - assets/myicons/icon-white-elevation.png
    - assets/myicons/icon-white-calories.png
    - assets/myicons/icon-white-time.png
    - assets/myicons/icon-white-speed-ometer.png
    - assets/myicons/icon-white-road.png
    - assets/myicons/icon-white-runner-02.png
    - assets/myicons/icon-black-path.png
    - assets/myicons/icon-black-love.png
    - assets/myicons/icon-black-bold-love.png
    - assets/myicons/icon-orange-bold-love.png
    - assets/myicons/icon-orange-love.png
    - assets/myicons/icon-white-love.png
    - assets/myicons/icon-black-comment.png
    - assets/myicons/icon-white-comment.png
    - assets/myicons/icon-black-share.png
    - assets/myicons/icon-white-share.png
    - assets/myicons/icon-white-bold-share.png
    - assets/myicons/icon-black-runner.png
    - assets/myicons/icon-white-runner.png
    - assets/myicons/icon-white-info.png
    - assets/myicons/icon-white-shoe.png
    - assets/myicons/icon-white-statistics.png
    - assets/myicons/icon-black-attachments-02.png
    - assets/myicons/icon-white-attachments-02.png
    - assets/myicons/icon-black-block.png
    - assets/myicons/icon-white-block.png
    - assets/myicons/icon-black-add-02.png
    - assets/myicons/icon-white-add-02.png
    - assets/myicons/icon-black-close.png
    - assets/myicons/icon-white-close.png
    - assets/myicons/icon-black-news-feed.png
    - assets/myicons/icon-black-post.png
    - assets/myicons/icon-white-post.png
    - assets/myicons/icon-black-3-dots.png
    - assets/myicons/icon-white-3-dots.png
    - assets/myicons/icon-black-gps.png
    - assets/myicons/icon-white-gps.png
    - assets/myicons/icon-black-key.png
    - assets/myicons/icon-white-key.png

    - assets/myicons/icon-white-light-record.png
    - assets/myicons/icon-yellow-light-record.png
    - assets/myicons/icon-white-events-02.png
    - assets/myicons/icon-yellow-events-02.png
    - assets/myicons/icon-white-news-feed-02.png
    - assets/myicons/icon-yellow-news-feed-02.png
    - assets/myicons/icon-white-profile-02.png
    - assets/myicons/icon-yellow-profile-02.png
    - assets/myicons/icon-white-teams.png
    - assets/myicons/icon-yellow-teams.png
    - assets/myicons/icon-white-settings.png
    - assets/myicons/icon-yellow-settings.png
    
    - assets/usrunlogo/app-icon.png
    - assets/usrunlogo/background.png
    - assets/usrunlogo/foreground.png
    - assets/usrunlogo/logo-text.png
    - assets/usrunlogo/logo.png


    - assets/myicons/icon-color-record-events.png
    - assets/myicons/icon-color-record-statistics.png
    - assets/myicons/icon-record-pause.png
    - assets/myicons/icon-record-restart.png
    - assets/myicons/icon-record-start.png
    - assets/myicons/icon-record-stop.png
    - assets/myicons/icon-white-record-events.png
    - assets/myicons/icon-white-record-statistics.png

    
    - assets/myicons/spot.gif
    - assets/myicons/icon-color-markeruser.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

