name: usrun
description: HCMUS Run

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  reflectable: any
  
  image_picker: ^0.6.1+8
  shared_preferences: ^0.5.0
  sprintf: ^4.0.2
  gradient_app_bar: ^0.1.3
  flutter_launcher_icons: ^0.7.4
  date_format: ^1.0.8
  
  path_provider: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter_icons:
  image_path: "assets/usrunlogo/app-icon.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/localization/en.json
    - assets/localization/vi.json

    - assets/images/welcome.png
    - assets/images/login_fb.png
    - assets/images/login_gg.png
    - assets/images/or_line.png
    - assets/images/login_email.png

    - assets/images/drawer_background.png
    - assets/images/drawer_background_darker.jpg
    - assets/images/avatar.png

    - assets/myicons/icon-white-back.png
    - assets/myicons/icon-orange-close.png
    - assets/myicons/icon-orange-search.png
    - assets/myicons/icon-big-white-check.png
    - assets/myicons/icon-white-image-default.png
    - assets/myicons/icon-black-image-default.png

    - assets/myicons/icon-white-record.png
    - assets/myicons/icon-white-events-02.png
    - assets/myicons/icon-white-news-feed-02.png
    - assets/myicons/icon-white-profile.png
    - assets/myicons/icon-white-teams.png
    - assets/myicons/icon-white-settings.png
    
    - assets/usrunlogo/app-icon.png
    - assets/usrunlogo/logo-text.png
    - assets/usrunlogo/logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

